### ISSUE TITLE
Create API for List of Vendors

### ISSUE THREAD

**Issue by sayyidfadhlillah** [sakinah-platform/backend-engine#10]
## User Story Description:

As a: Frontend Engineer
I want to: retrieve list of vendors in Sakinah
So that: I can see all vendors that are available to assist my wedding

## Acceptance Criteria

Each vendor data is displayed as follows:

1. Vendor Profile Image 
2. Vendor Name
3. Key Information - Starting Price

Vendors can be filtered:

1. by Category
2. by Price
3. by City

Vendors can be searched:

1. by Vendor Name

## Definition of done

- Data can be displayed as it is defined
- The filter functionality work as expected
- The search functionality work as expected

**Comment by ayaar25** [comment]
Django Filtering Lib https://django-filter.readthedocs.io/en/latest/guide/usage.html#the-model

**Comment by ayaar25** [comment]
We don't save the vendor's address information. By City filter is deferred.
